package:
  name: pgdb
  version: 2.0.0
requirements:
  build:
  - python
  - setuptools
  - psycopg2
  - sqlalchemy
  run:
  - python
source:
  path: /home/ralbright/pgdb/dist
about:
  license: MIT License
  summary: pgdb database connector
